### ISSUE TITLE
Help with build...

### ISSUE THREAD

**Issue by MrMxyzptlk** [Saghen/open-library-proxy#12]
So I have the docker compose containers running in Docker Desktop for Windows with WSL / Ubuntu
I then went into WSL / Ubuntu and cloned this repo.
bash build.sh only 'restored' some proj files? A couple failed to restore; NzbDron.Common/Readarr,Common.csproj and Readarr.Care

Any assistance with building this would be appreciated.

Thank you.

**Comment by saghen** [comment]
Hey, this is for the open library proxy but it sounds like you're trying to build Readarr, I can't help you there sorry

**Comment by MrMxyzptlk** [comment]
Afterwards, you can build [my fork of Readarr](https://github.com/saghen/readarr) locally.

I'm trying to build your fork of Readarr...
